version: "3.9"

services:
  app:
    image: jarebear/picklist:latest
    container_name: picklist_app
    depends_on:
      - db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password
      POSTGRES_HOST: db        # docker-internal hostname
      POSTGRES_PORT: 5432
      POSTGRES_DB: picklist
      TZ: America/Winnipeg
    ports:
      - "5000:5000"
    volumes:
      - /mnt/rootshare/PickList:/app/data  # persistent app data folder

  db:
    image: postgres:18
    container_name: picklist_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: picklist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password
      TZ: America/Winnipeg
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # exposed for local dev tools (DBeaver, TablePlus, etc.)

volumes:
  pgdata:
