services:
  app:
    image: jarebear/thepantry:latest
    container_name: thepantry_app
    depends_on:
      - db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: thepantry
      TZ: America/Winnipeg
      PORT: 5010
      DATA_PATH: /app/data
    ports:
      - "5010:5000"
    volumes:
      - /mnt/rootshare/ThePantry:/app/data

  db:
    image: postgres:16
    container_name: thepantry_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: thepantry
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password
      TZ: America/Winnipeg
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
