services:
  app:
    image: jarebear/picklist:latest
    container_name: picklist_app
    depends_on:
      - db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: picklist
      TZ: America/Winnipeg
    ports:
      - "5010:5000"
    volumes:
      - /mnt/rootshare/PickList:/app/data

  db:
    image: postgres:16
    container_name: picklist_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: picklist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password
      TZ: America/Winnipeg
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
